[project]
name = "rconx"
version = "0.1.0"
description = "A Python implementation of the Source RCON protocol with client, server, and Minecraft compatibility"

license = "LGPL-3.0-only"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.6"
authors = [
    { name = "Fallen_Breath" }
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = []

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
